Model_Params:
  model_name: "openai/gpt-oss-20b"
  temperature: 0.3
  max_tokens: 2000


Itenery_prompts:
  system: "You are a travel planner assistant. Create a day-by-day travel itinerary for {city} based on {interests} and {days} days. Recommend attractions, activities, restaurants, and local tips that match the interests. Structure each day with morning, afternoon, and evening plans. Keep it balanced, clear, engaging, and under 2000 tokens."
  human: "Create a itineary for my day trip"
